apiVersion: v1
kind: PersistentVolume
metadata:
  name: upload-efs-pv
spec:
  capacity:
    storage: 200Gi
  volumeMode: Filesystem
  claimRef:
    name: upload-efs-claim
    namespace: default
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{efs id}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: upload-efs-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 200Gi
