---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gradle-repo-pv
  labels:
    type: local
spec:
  storageClassName: local-storage
  claimRef:
    name: gradle-repo-pvc
    namespace: devops-tools
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  local:
    path: /mnt
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - <hostname>

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gradle-repo-pvc
  namespace: devops-tools
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi