---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-logstash
  namespace: default
  labels:
    app: my-logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-logstash
  template:
    metadata:
      labels:
        app: my-logstash
    spec:
      containers:
        - image: {{imagehost}}/real-my/logstash:0.0.4
          imagePullPolicy: Always
          name: my-logstash
          resources:
            requests:
              memory: "1000Mi"
              cpu: "1000m"
            limits:
              memory: "2000Mi"
              cpu: "1000m"
          ports:
            - name: syslogport
              containerPort: 4560

---
apiVersion: v1
kind: Service
metadata:
  name: my-logstash-svc
  namespace: default
  labels:
    app: my-logstash-svc
spec:
  ports:
    - port: 4560
      protocol: TCP
      targetPort: 4560
  selector:
    app: my-logstash
  type: ClusterIP
