apiVersion: v1
kind: PersistentVolume
metadata:
  name: adot-collector-efs-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  claimRef:
    name: adot-collector-efs-claim
    namespace: fargate-container-insights
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{efs volume id}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adot-collector-efs-claim
  namespace: fargate-container-insights
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
